### ISSUE TITLE
To-dos

### ISSUE THREAD

**Issue by perploug** [zalando-incubator/kube-metrics-adapter#1]
- [ ] [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) updated
- [ ] [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md) updated with names of external contributors
- [ ] [CODEOWNERS](../blob/master/.github/CODEOWNERS) updated with usernames of who review which PRs
- [ ] [MAINTAINERS](../blob/master/MAINTAINERS) updated with team member contact info
- [ ] [CODE_OF_CONDUCT.md](../blob/master/CODE_OF_CONDUCT.md) reviewed
- [ ] [SECURITY.md](../blob/master/SECURITY.md) reviewed
- [ ] [Pull request template](../blob/master/.github/PULL_REQUEST_TEMPLATE.md) reviewed
- [ ] [Issue template](../blob/master/.github/ISSUE_TEMPLATE.md) reviewed
- [ ] [Readme](../blob/master/README.md) updated

**Comment by arjunrn** [comment]
Only the `CONTRIBUTORS.md` file needed to be updated. The rest of the files seemed to be in order.
