### ISSUE TITLE
Any chance to update the AWS Go SDK to support IAM For Service Accounts?

### ISSUE THREAD

**Issue by badbeeker** [zalando-incubator/kube-metrics-adapter#105]
Any chance the AWS go SDK could be updated to support IAM for Service Accounts?  Would go a long way for us EKS users or anyone running on AWS.  That way we don't need to run Kube2IAM or KIAM in the cluster.

Thank you!

**Comment by mikkeloscar** [comment]
Sure, no problem. We're currently testing this out ourselves so we will also need it. Made a PR to fix it :)
