### ISSUE TITLE
[Metric-Config] Support for passing query params to pod metrics endpoint

### ISSUE THREAD

**Issue by doyshinda** [zalando-incubator/kube-metrics-adapter#108]
## Expected Behavior
Ability to add URL query parameters (`foo=bar&baz=bop`) to the metrics config json-path to be passed on to the pod's metric endpoint.

## Actual Behavior
There is no explicit option to pass query parameters to the endpoint defined when collecting pod metrics. Appending the query to the `path` config option results in Go correctly percent encoding the `?` because it is a [reserved character](https://tools.ietf.org/html/rfc3986#section-2.2):
```
metric-config.pods.concurrency-average.json-path/path: /metrics?foo=bar
```
will generate the following URL:
```
http://<podIP>:<port>/metrics%3Ffoo=bar
```
This results in the application not using the `?` as delimiter and usually returning a 400 (or ignorning the query params).

## Steps to Reproduce the Problem

  1. Setup a custom API that expects query params
  2. Setup json-path to add those query params: `...json-path/path: /metrics?foo=bar`
  3. Observe that the k8s autoscaler reports: `unable to get metric <metric>: unable to fetch metrics from custom metrics API: the server is currently unable to handle the request (get pods.custom.metrics.k8s.io *)`

## Specifications
  - Version: 0.0.5

**Comment by doyshinda** [comment]
Hi, I have a change locally that adds support to add a new parameter to json-path named `rawQuery`. This value is plumbed through to Go's `net/URL` [struct](https://golang.org/pkg/net/url/#URL) as `RawQuery` to allow passing query params to pod endpoints.

If this is an acceptable approach, I will put up a PR here.

**Comment by mikkeloscar** [comment]
Sounds reasonable to me. Please create a PR then we can discuss the details there.
