### ISSUE TITLE
Errors in logs when attempting to query a label value which doesn't exist

### ISSUE THREAD

**Issue by dudicoco** [zalando-incubator/kube-metrics-adapter#144]
When using an external metrics with a query such as the following:
```
http_requests_total{status="5xx"}
```

If no `5xx` events have been registered yet, we get the following in the logs:
```
level=error msg="Failed to collect metrics: query 'http_requests_total{status=\"5xx\"}\n' did not result a valid response" provider=hpa
```

Perhaps this should be a `warning` instead of `error`? Considering that this label value can be updated at any time.

**Comment by szuecs** [comment]
Can you try to use max(0, query), not sure about syntax but maybe a more safe query.

**Comment by dudicoco** [comment]
@szuecs thanks, sounds like a proper solution.

**Comment by dudicoco** [comment]
For anyone interested, another solution could be the `absent` function:
https://prometheus.io/docs/prometheus/latest/querying/functions/#absent
