### ISSUE TITLE
add release notes

### ISSUE THREAD

**Issue by szuecs** [zalando-incubator/kube-metrics-adapter#16]
The current workflow to release this project does not include any release notes.
To document for us and the public audience we should use GH releases and set up release notes similar we do in in skipper, for example: https://github.com/zalando/skipper/releases/tag/v0.10.122

**Comment by hjacobs** [comment]
Yes, please create proper releases!

**Comment by mohanr** [comment]
I am looking for some guidelines to use this practically. How ?

**Comment by szuecs** [comment]
@mohanr this issue is not about guidelines

**Comment by mikkeloscar** [comment]
We now have the first official release: https://github.com/zalando-incubator/kube-metrics-adapter/releases/tag/v0.0.1
