### ISSUE TITLE
Templates from Doc folder gives some 403 errors 

### ISSUE THREAD

**Issue by karthikborkar** [zalando-incubator/kube-metrics-adapter#17]
I was able to bring up pod with the template and only thing i changed was Prometheus URL
to :  --prometheus-server=http://prometheus.monitoring.svc.cluster.local:9090

I see the bunch of errors 

`
time="2018-12-07T19:26:19Z" level=error msg="horizontalpodautoscalers.autoscaling is forbidden: User \"system:serviceaccount:kube-system:custom-metrics-apiserver\" cannot list horizontalpodautoscalers.autoscaling at the cluster scope" provider=hpa
`

`
E1207 19:26:21.268780       1 writers.go:149] apiserver was unable to write a JSON response: expected pointer, but got nil
E1207 19:26:21.268808       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"expected pointer, but got nil"}
`

Custom and external metrics are empty
`(venv) [ec2-user@ip-10-230-198-112 qaas]$ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" --kubeconfig=config-demo| jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": []
}`

`(venv) [ec2-user@ip-10-230-198-112 qaas]$ kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1" --kubeconfig=config-demo| jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": []
}
`

I have prometheus server running and it has metrics if i do
curl http://prometheus.monitoring.svc.cluster.local:9090/mertics

## Specifications

  - Version: K8s 1.11.0
  - Platform: KOPS k8s cluster

**Comment by mikkeloscar** [comment]
Thanks for creating the issue, the RBAC configuration is outdated/wrong. I have made a PR to fix it: https://github.com/zalando-incubator/kube-metrics-adapter/pull/18
