### ISSUE TITLE
Failed to collect metrics: client_error: client error: 401

### ISSUE THREAD

**Issue by ehsanrocket** [zalando-incubator/kube-metrics-adapter#182]
Hi all 
I have setup the kube-metrics-adapter 
but when it want to get the metrics it says :
```Failed to collect metrics: client_error: client error: 401```
what is the problem ? 

myapp and hpa are in the namespace **A**
kube-metrics-adapter is in namespace **kube-sysetem**
and prometheus adapter is in namespace **cattle-promethus**

**Comment by szuecs** [comment]
Sounds like RBAC does not allow it to get the HPA metrics to me

**Comment by ehsanrocket** [comment]
yeah 
prometheus operator has been deployed by rancher and the I should have pass the access-prometheus service to the the adapter CLI argument
