### ISSUE TITLE
Scrape Interval

### ISSUE THREAD

**Issue by felixPG** [zalando-incubator/kube-metrics-adapter#214]
Hi:

I loved the improvements over prometheus-adapter. Actually querying through an annotation is a brilliant idea. The problem is that the scrape interval is too slow and therefore the HPA is very very slow (delayed a lot). For this reason I go back to prometheus-adapter.

Please, could you add an option to config the scrape (query to prometheus) interval??? By scrape interval I mean the time that the adapter delay between scrapes from prometheus to publish the metrics in the k8s API server.

BTW, by default what is the scrape (query to prometheus) interval time??

Regards and nice work!!

**Comment by mikkeloscar** [comment]
@felixPG This is unfortunately not documented but there is a way to set the interval via an annotation like:

```yaml
metric-config.external.prometheus-query.prometheus/interval: 30s
```

Default is 1 minute.

**Comment by felixPG** [comment]
@mikkeloscar Great news! Thanks so much, I will try this annotation, but please, could you update the doc to reflect this?
