### ISSUE TITLE
(get pods.custom.metrics.k8s.io *) fails

### ISSUE THREAD

**Issue by benor1470** [zalando-incubator/kube-metrics-adapter#218]
## Expected Behavior
apply the yamls from https://github.com/zalando-incubator/kube-metrics-adapter/tree/master/docs
run my service which exposes metrics
get auto scales

## Actual Behavior
no autoscale,
when I ran
"kubectl describe hpa my-hpa"
getting 

  AbleToScale    True    SucceededGetScale    the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetPodsMetric  the HPA was unable to compute the replica count: unable to get metric web-active-request: unable to fetch metrics from custom metrics API: the server is currently unable to handle the request (get pods.custom.metrics.k8s.io *)

  Warning  FailedGetPodsMetric           7m58s (x153 over 163m)  horizontal-pod-autoscaler  unable to get metric web-active-request: unable to fetch metrics from custom metrics API: the server is currently unable to handle the request (get pods.custom.metrics.k8s.io *)
  Warning  FailedComputeMetricsReplicas  2m56s (x158 over 163m)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get pods metric value: unable to get metric web-active-request: unable to fetch metrics from custom metrics API: the server is currently unable to handle the request (get pods.custom.metrics.k8s.io *)

## Steps to Reproduce the Problem
install a new k8s cluster, apply

1)deployment.yaml
2)rbac.yaml
3)service.yaml
4)custom-metrics-apiservice.yaml
from https://github.com/zalando-incubator/kube-metrics-adapter/tree/master/docs 

then my config yaml
[myDep.yaml.txt](https://github.com/zalando-incubator/kube-metrics-adapter/files/5451546/myDep.yaml.txt)

my service returns {"active":30} when calling
http://url:8181/k8sMetrics?json

I expect the issue to be related to versions,
the example refers to 

> apiVersion: autoscaling/v2beta2

but custom-metrics-apiservice.yaml refers to
>   name: v1beta1.custom.metrics.k8s.io

tried to change version but it didn't help

I'm not a k8s expert, understood you don't have helm so I expected a simple yaml to setup the environment not sure what I did wrong

**Comment by mikkeloscar** [comment]
Can you show the logs of the kube-metrics-adapter. Sounds like it's either not running or returning errors.

**Comment by benor1470** [comment]
came back to the issue and managed to run, so there is no bug
