### ISSUE TITLE
external metrics are not namespace scoped for prometheus 

### ISSUE THREAD

**Issue by mad01** [zalando-incubator/kube-metrics-adapter#255]
## Expected Behavior
Assuming you have two different deployment of the same application running in the same cluster but in different namespaces. You define the same query name like this. hpa 1 and 2 use the same name. The expected result for me is that the hpas in different namespaces are not ware of each other and cant interfere.

hpa 1
```yaml
    metric-config.external.fr-hpa-http-requests.prometheus/query: |
      scalar(sum(rate(fr_hpa_testing_http_requests_total{kubernetes_namespace="alpha"}[5m])))
``` 

hpa 2
```yaml
    metric-config.external.fr-hpa-http-requests.prometheus/query: |
      scalar(sum(rate(fr_hpa_testing_http_requests_total{kubernetes_namespace="beta"}[5m])))
``` 

## Actual Behavior
Since they use the same name and you see one registered external metric they interfere with each other and the HPA scales on the same metric not differently 

example output showing this 
```bash
fr-hpa-testing main ? ❯❯❯ k get hpa -A 
NAMESPACE   NAME                 REFERENCE                   TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
alpha       fr-hpa-testing-hpa   Deployment/fr-hpa-testing   14440m/50 (avg)   1         3         1          37m
beta        fr-hpa-testing-hpa   Deployment/fr-hpa-testing   14440m/50 (avg)   1         3         1          37m
fr-hpa-testing main ? ❯❯❯ kubectl get -A  --raw "/apis/external.metrics.k8s.io/v1beta1" | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "fr-hpa-http-requests",
      "singularName": "",
      "namespaced": true,
      "kind": "ExternalMetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}

```

## Specifications

  - Version: 2bfc85ff3d48039d8f36af8d8aee64b204e99048
  - Platform: k8s 1.17
  - Subsystem:

**Comment by mad01** [comment]
duplicate of #229

**Comment by mad01** [comment]
i am trying to understand the code, to try to get some understanding of how complicated this would be to fix. Do you have any suggestion on how or if this is a reasonable thing to fix ?

**Comment by mikkeloscar** [comment]
Hi, I did start working on this back in November, but never got around to finish up the changes.

I have now pushed my unfinished changes here which may serve as a starting point if you're interested in working on a proper fix: https://github.com/zalando-incubator/kube-metrics-adapter/compare/master...namespace-external-metrics

**Comment by mad01** [comment]
Cool thank you. will take a look. hoping to be able to get some time to work on it

**Comment by mad01** [comment]
I did not get that far last week, but looks like i wont have time to work on the atm at least. Here is the branch i with the changes i was able to do. The changes are only related to getting tests to pass before i started. 
https://github.com/mad01/kube-metrics-adapter/tree/namespace-external-metrics

**Comment by mikkeloscar** [comment]
I have now opened a PR #259 to get this work finally done. I will work on it next week.

**Comment by mikkeloscar** [comment]
@mad01 I managed to get #259 working. You can try it out with the image built from the PR: `registry.opensource.zalan.do/teapot/kube-metrics-adapter-test:pr-259-7`

**Comment by mad01** [comment]
sorry for the late reply. thank you for taking the time. will try it out next week
