### ISSUE TITLE
Metric Resolution Flag

### ISSUE THREAD

**Issue by robertbotez** [zalando-incubator/kube-metrics-adapter#296]
Hi,

I can set  the flag in the metric-server, thus I can query for the predefined metrics (CPU and memory) more quickly (10s, 30s and so on). I want to do this too for the custom and external metrics, because they are queried once in a minute. 

Is there a way to set the metric-resolution flag for the custom and external metrics?

Thank you.

**Comment by mikkeloscar** [comment]
This can be set via an annotation on the HPA. #298 aims to make this more clear in the docs!
