### ISSUE TITLE
Support for AWS collector from external cluster

### ISSUE THREAD

**Issue by jonathangold** [zalando-incubator/kube-metrics-adapter#35]
I need to scale based on sqs queue length, but my cluster will be running on GKE (or locally,) and I'm not 100% sure if this use-case is supported yet. Can I just add the aws credentials to env, and get it working externally?

**Comment by mikkeloscar** [comment]
Yup, that should work, it just uses the AWS SDK for access to SQS, so any valid way of configuring the SDK should work (not tested though).

**Comment by jonathangold** [comment]
@mikkeloscar thanks for the quick reply. Once I get it working, I'll submit a PR to document the process.

**Comment by mikkeloscar** [comment]
> @mikkeloscar thanks for the quick reply. Once I get it working, I'll submit a PR to document the process.

Awesome! Looking forward to it!

**Comment by jonathangold** [comment]
@mikkeloscar I've started on my deployment, but I'm getting the following error on the kube-metrics-adapter pod:

```
time="2019-02-21T21:41:53Z" level=info msg="Event(v1.ObjectReference{Kind:\"HorizontalPodAutoscaler\", Namespace:\"omitted\", Name:\"omitted-hpa\", UID:\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\", APIVersion:\"autoscaling/v2beta1\", ResourceVersion:\"XXXXXX\", FieldPath:\"\"}): type: 'Warning' reason: 'CreateNewMetricsCollector' Failed to create new metrics collector: no plugin found for {External sqs-queue-length}"
```
I tried tracing the code-path, but didn't have much luck. Am I missing something obvious. Thanks in advance.

**Comment by mikkeloscar** [comment]
Are you setting the `--aws-external-metrics` and `--aws-region` flags?

https://github.com/zalando-incubator/kube-metrics-adapter/blob/f4efa2898be17cc4482702a363136f0778551869/pkg/server/start.go#L203-L209

https://github.com/zalando-incubator/kube-metrics-adapter/blob/f4efa2898be17cc4482702a363136f0778551869/pkg/server/start.go#L211-L213

**Comment by jonathangold** [comment]
That was the issue. It's working now! thanks!
