### ISSUE TITLE
Scale pods with metrics from other pods

### ISSUE THREAD

**Issue by narayanansukumar** [zalando-incubator/kube-metrics-adapter#41]
I have implemented HPA based on metrics server (based on memory and CPU), however, it is not suitable for my use case and I'd like to scale the pods (logstash) based on KAFKA consumer lag, I have the metrics in Prometheus that is running inside the k8s cluster under a different namespace.

Prometheus query for getting the metrics:
sum(kafka_consumergroup_lag{instance="xxxx:9308",consumergroup=~"solr-large-consumer"}) by (consumergroup, topic)

Currently, I am able to get these metrics with some other applications in json format. Can I scale the logstash pods with the metrics from the different pods?

**Comment by arjunrn** [comment]
You don't need to expose these metrics from the pod because there is already a Prometheus collector which you can specify in the HPA. The metrics adapter will then query this metric and expose it as a custom metric.

**Comment by mikkeloscar** [comment]
Closing as this was a question which has been answered. Please re-open if something is still unclear.
