### ISSUE TITLE
Helm chart should be available in a chart repository

### ISSUE THREAD

**Issue by prune998** [zalando-incubator/kube-metrics-adapter#431]
## Expected Behavior
Helm chart should be available in a chart repository (https://helm.sh/docs/topics/chart_repository/ and https://artifacthub.io/docs/topics/repositories/#helm-charts-repositories) so we can use it by using chart `dependencies`

## Actual Behavior
the helm chart needs to be downloaded from this repo to be used

**Comment by prune998** [comment]
https://helm.sh/docs/topics/chart_repository/#github-pages-example could help achieve that quickly. I can help too

**Comment by mikkeloscar** [comment]
> I can help too

That would be very welcome. We don't use helm ourselves, but happy to support it if it's not too much effort.

**Comment by mikkeloscar** [comment]
Configured it like this:

![image](https://user-images.githubusercontent.com/128566/167919072-dd65d4fc-763d-46af-bb2e-18c1b88c0dfa.png)

**Comment by prune998** [comment]
Thanks @mikkeloscar 
It seems it would be easier to maintain the chart in another branch (like `gh-pages`) else it's more complicated to trigger on a change on master, as updating the chart index is also a change on master...
I'm new to setting this up, and trying different things, but the easier would be to change the branch.

I'm building up a PR for the action and the other files.

**Comment by prune998** [comment]
PR at https://github.com/zalando-incubator/kube-metrics-adapter/pull/432 but needs Pages to be served from the `gh-pages` branch first.
Thanks !

**Comment by antoinedeschenes** [comment]
v0.2.0 was just released to the helm repository https://github.com/zalando-incubator/kube-metrics-adapter/releases/tag/kube-metrics-adapter-0.2.0

**Comment by mikkeloscar** [comment]
Closing as this is now in place. Thanks everyone invovled!
