### ISSUE TITLE
Prometheus collector should create External target.type

### ISSUE THREAD

**Issue by timstoop** [zalando-incubator/kube-metrics-adapter#45]
## Expected Behavior
I think it makes more sense for the Prometheus collector to create an External metric instead of an Object. The syntax fits better. Also, although it can provide metrics about an Object, I doubt it will be used much in that way.

## Actual Behavior
It currently provides the metrics of type Object. So a dummy target has to be added and for Kubernetes <1.12 targetAverageValue requires a workaround.

**Comment by mikkeloscar** [comment]
Hi, thanks for opening the issue (sorry for not getting back sooner). I agree that External metric makes sense for prometheus and I would add that as a second option to stay backward compatible at least for long enough for users to migrate.
