### ISSUE TITLE
Is it possible to retrieve request per second to pod without using prometheus?

### ISSUE THREAD

**Issue by smartaquarius10** [zalando-incubator/kube-metrics-adapter#478]
Hello,

I dont have any observability app in my kubernetes environment. By any chance is it possible to retrieve the http request per second to pod without using such apps like prometheus, datadog etc. 

Thank you

**Comment by szuecs** [comment]
It's not what this project provides. In general you can export metrics in your application or proxy without collecting (f.e. Prometheus).
These metrics can provide rps as you want.
We don't provide support on this.

**Comment by mikkeloscar** [comment]
If your app exposes a json endpoint with the metric then you can use the http collector to get the metric and scale based on that.

**Comment by smartaquarius10** [comment]
@mikkeloscar, Oh ok.. Thank you so much.. 

@mikkeloscar,@szuecs, How to setup this adapter. If I setup this without prometheus then what to do with this line 

https://github.com/zalando-incubator/kube-metrics-adapter/blob/9e057c107538cc00818ec24e42a5ae1c311902e8/docs/deployment.yaml#L28

**Comment by szuecs** [comment]
The adapter just enables you to get the metrics from different sources. One is Prometheus and if you don't want that you just don't use this flag.
