### ISSUE TITLE
Missing Documentation for kubernetes compatibility matrix

### ISSUE THREAD

**Issue by aknam** [zalando-incubator/kube-metrics-adapter#517]
## Expected Behavior
Documentation for kubernetes compatibility matrix with kube metric adapter
We are upgrading kubernetes to 1.22 release and we could not found any documentation of kube metric adapter release which is compatible with the kubernetes release 1.22 

## Actual Behavior
Missing Documentation

**Comment by mikkeloscar** [comment]
In the README.md we indicate the minimum version supported for the different collectors. If nothing is stated it's assumed it works with all bigger versions.

We don't have the infrastructure to cross test all versions, but unless users report that it does _not_ work with a specific version it's fair to assume that it will work.

We're currently working on upgrading to v1.22 as well and have not encountered issues related to kube-metrics-adapter.

I will close this issue for now, but feel free to comment if you do happen to find issues with v1.22 that we haven't observed.
