### ISSUE TITLE
Update k8s autoscaling dependency to v2 version to support Kubernetes 1.26+

### ISSUE THREAD

**Issue by slivarez** [zalando-incubator/kube-metrics-adapter#550]
## Expected Behavior

Use `autoscaling/v2` apiVersion to watch HPA objects.

## Actual Behavior

`autoscalingv2 "k8s.io/api/autoscaling/v2beta2"` is used currently

`autoscaling/v2beta2` [has been removed from Kubernetes v1.26](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126)

## Steps to Reproduce the Problem

  1. Run Kubernetes 1.26+
  1. Collector won't be able to pull HPA objects

## Specifications

  - Version: v0.1.17
  - Platform: Kubernetes
  - Subsystem: N/A

**Comment by mikkeloscar** [comment]
This is solved in the latest release: https://github.com/zalando-incubator/kube-metrics-adapter/releases/tag/v0.2.0

Fixed in #551
