### ISSUE TITLE
Is that feasible to run the adapter into a namespace different from `kube-system`?

### ISSUE THREAD

**Issue by paoloyx** [zalando-incubator/kube-metrics-adapter#564]
Hi, I'm currently running a `v0.1.10` version of `kube-metrics-adapter` into a GKE cluster and, as expected from chart's default values, it was installed into `kube-system` namespace.

I'm currently facing a situation where the `kube-metrics-adapter` is blocking a scaleDown of the cluster with a `no.scale.down.node.pod.kube.system.unmovable` reason.

Looking at [GKE documentation](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-to-set-pdbs-to-enable-ca-to-move-kube-system-pods) it seems clear that I should add a _PodDisruptionBudget_ to ensure that a proper scale down can happen.

> By default, kube-system pods prevent CA from removing nodes on which they are running. Users can manually add PDBs for the kube-system pods that can be safely rescheduled elsewhere:

But the `kube-metrics-adapter` is running in single replica mode (and I think cannot run in different ways than that, is it right? To avoid race conditions?) and so the PDB is of no help.

So my question is:

* Can `kube-metrics-adapter` run in multi-replica mode?
* Otherwise, can I deploy it to a different namespace than `kube-system` without problems?

Looking at chart template files for the latest release (to which we can upgrade) it seems to me that the second option is a viable one. 

But I'm also looking for advice of you, experts of the matter, thanks :)

**Comment by antoinedeschenes** [comment]
It supports running in another namespace. 

The `PodDisruptionBudget` workaround might work with `maxUnavailable: 1`, that usually has no action, but maybe in the case of `kube-system`, that removes the `unmovable` condition.

**Comment by mikkeloscar** [comment]
> Can kube-metrics-adapter run in multi-replica mode?

It's not designed to do that as it has an internal cache that could be different between replicas. If the single replica is unavailable the HPA will simply not scale based on the related metrics for the time being.

Since using a different namespace is the best suggestion for this issue I will close this one.

**Comment by paoloyx** [comment]
@antoinedeschenes @mikkeloscar thanks for the advice
