### ISSUE TITLE
Docker image for arm64 not published

### ISSUE THREAD

**Issue by wndhydrnt** [zalando-incubator/kube-metrics-adapter#596]
## Expected Behavior
When pulling `registry.opensource.zalan.do/teapot/kube-metrics-adapter:v0.2.1` on a host that runs on architecture arm64, Docker pulls an image compatible with arm64.

## Actual Behavior
Docker pulls the Docker image for architecture amd64.

## Steps to Reproduce the Problem

Steps executed on a host that runs on architecture arm64 and has Docker Desktop installed, e.g. a MacBook.

Docker prints a warning when running the latest release:
  1. `docker pull registry.opensource.zalan.do/teapot/kube-metrics-adapter:v0.2.1`
  1. `docker run --rm -it registry.opensource.zalan.do/teapot/kube-metrics-adapter:v0.2.1`
Output:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Launch the custom metrics API adapter server

Usage:
...
```

It looks like `docker buildx build` is set up correctly in [delivery.yaml](https://github.com/zalando-incubator/kube-metrics-adapter/blob/bbfd982fb6d7c4f08c7a97fef646982356dbf8de/delivery.yaml#L45). However, `docker manifest inspect registry.opensource.zalan.do/teapot/kube-metrics-adapter:v0.2.1` does not return a Manifest List for multiple architectures, but a single Manifest.

## Specifications

  - Version: v0.2.1
  - Platform: arm64
  - Subsystem: N/A

**Comment by mikkeloscar** [comment]
> It looks like docker buildx build is set up correctly in [delivery.yaml](https://github.com/zalando-incubator/kube-metrics-adapter/blob/bbfd982fb6d7c4f08c7a97fef646982356dbf8de/delivery.yaml#L45).

This is the setup only for internal images which are not public unfortunately. The public image is currently on `registry.opensource.zalan.do` which doesn't support multi-arch images.

The way forward here would be to host multi-arch images on docker hub or Github Container Registry.
