### ISSUE TITLE
Comparison of Pod Collector to PodMonitor

### ISSUE THREAD

**Issue by StevenACoffman** [zalando-incubator/kube-metrics-adapter#60]
While the difference between the [Prometheus Collector](https://github.com/zalando-incubator/kube-metrics-adapter#prometheus-collector) and the [Prometheus Adapter](https://github.com/DirectXMan12/k8s-prometheus-adapter) is documented, I am interested in a comparison of the **[Pod Collector](https://github.com/zalando-incubator/kube-metrics-adapter#pod-collector)** and the experimental **[PodMonitor](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#podmonitor).**

Recently, the prometheus operator got the concept of a PodMonitor: https://github.com/coreos/prometheus-operator/pull/2566

The primary use case of a PodMonitor is scraping Pods _directly_ without needing an explicit association to any specific service, as in sidecars shared by several services. For example, I want to generically scape all Istio sidecars.

+ [Pod Monitor](https://github.com/coreos/prometheus-operator/pull/2566)
+ [Pod Collector](https://github.com/zalando-incubator/kube-metrics-adapter#pod-collector)

**Comment by mikkeloscar** [comment]
As I understand it, these two concepts are different in the way that `PodMonitor` is "just" a way to configure prometheus to scrape metrics from pods, while `Pod Collector` is a way of scraping metrics ONLY for the purpose of autoscaling with the Kubernetes HPA.

Right now `Pod Collector` only supports JSON, so you can't use it for a pod that exposes metrics in prometheus format.

Assuming the `Pod Collector` did support prometheus format, then the difference would be that you collect the metrics directly into the Kubernetes HPA infrastructure and let Kubernetes HPA average the metrics across all pods and autoscale based on this. This way you could omit Prometheus if you don't need it for other things.

However, using the `PodMonitor` for scraping metrics you could aggregate the metrics in prometheus and do much more advanced queries. Queries which you could scale on using the `Prometheus Collector`.

Hope it make sense.

**Comment by mikkeloscar** [comment]
I'll close this issue as "answered" :)
