### ISSUE TITLE
Docs on using HTTPS with Pod collector

### ISSUE THREAD

**Issue by samirgandhi19** [zalando-incubator/kube-metrics-adapter#62]
## Expected Behavior
Add as an annotation: 
`metric-config.pods.requests-per-second.json-path/protocol: "https"`
to have the pod collector reach out to an https pod endpoint. 

## Actual Behavior
I couldn't find a way to achieve this. If there is **any** way to have the hpa use https, please let me know. Thank you.

**Comment by mikkeloscar** [comment]
Documented in #63
