### ISSUE TITLE
Current helm charts does not work

### ISSUE THREAD

**Issue by johnzheng1975** [zalando-incubator/kube-metrics-adapter#727]
Current helm charts does not work ./docs/helm
You can install it successfully, but never work.
If you run `cd docs; kubectl apply -f .`, it can work.

If you view the helm charts, the version is old.
The values are not expected.
Even some status inside. 

It may not professional enough for such a good product.

 
## Specifications

  - Version: v0.2.2 +
  - Platform:
  - Subsystem:

**Comment by szuecs** [comment]
Thanks for the issue and fix!
We don't use helm and likely it was contributed years ago.

**Comment by johnzheng1975** [comment]
Thanks for merge my PR.
Is it possible to create a new tag,  Or delete old v0.2.2 release and retag?

Currently, when I refer as below, will still use old code which is tagged in Dec 7, 2023.
![image](https://github.com/zalando-incubator/kube-metrics-adapter/assets/17720035/ef7e63d0-7215-4ef6-9f6e-3b59b4abda24)


![image](https://github.com/zalando-incubator/kube-metrics-adapter/assets/17720035/af933268-07f8-4261-a8c3-fb0be9dc7ed4)
