### ISSUE TITLE
Latest version v0.2.3 not found

### ISSUE THREAD

**Issue by ebeltramo96** [zalando-incubator/kube-metrics-adapter#731]
## Expected Behavior

being able to pull: `registry.opensource.zalan.do/teapot/kube-metrics-adapter:v0.2.3`

## Actual Behavior

Hello, it has already 2 weeks since the new release have been pushed but I'm still not able to pull that image:

`docker: Error response from daemon: manifest for registry.opensource.zalan.do/teapot/kube-metrics-adapter:v0.2.3 not found: manifest unknown: manifest unknown.`

same way if we push the new helm chart version to our Kubernetes cluster it will result in a ImagePullBackOff error:

## Steps to Reproduce the Problem

  1. `docker pull registry.opensource.zalan.do/teapot/kube-metrics-adapter:v0.2.3` -> not working for 2 weeks
  1. `docker pull registry.opensource.zalan.do/teapot/kube-metrics-adapter:v0.2.2` -> previous version still working

## Specifications

  - Version: v0.2.3
  - Platform: docker/kubernetes

**Comment by mikkeloscar** [comment]
The build is now fixed and there is an image for v0.2.3

**Comment by szuecs** [comment]
If you found this and can't fetch the container, please check https://github.com/zalando-incubator/kube-metrics-adapter/issues/804#issuecomment-2886542977
