### ISSUE TITLE
[Metric-Config] JsonPath support string indexers for json prop keys with dots

### ISSUE THREAD

**Issue by andrealexandre** [zalando-incubator/kube-metrics-adapter#91]
## Expected Behavior
When setting up metric configs using jsonpath, it's expected to support the regular jsonpath expression.

## Actual Behavior
The actual behaviour is in the case of using string indexers for accessing json props with `.`'s in them, the jsonpath lib is not able to extract the value and go into the value.

https://github.com/zalando-incubator/kube-metrics-adapter/blob/master/pkg/collector/json_path_collector.go#L13

## Steps to Reproduce the Problem

  1. Setup a json-path/json-key value with something like: `$.histograms['service.pool.Usage']mean`
  2. On k8s the autoscaler will report: `Failed to create new metrics collector: format '' not supported`

## Specifications

  - Version: latest

**Comment by andrealexandre** [comment]
Please let me know if you need more information. I'm more than happy to help.

**Comment by szuecs** [comment]
@andrealexandre thanks for creating the issue. @arjunrn is right now at Kubecon, but he will follow up on this.

**Comment by dushshantha** [comment]
I ran into the same issue. Any update on this? I am using the latest version.

**Comment by dushshantha** [comment]
@andrealexandre Were you able to find any workaround for this?

**Comment by andrealexandre** [comment]
> @andrealexandre Were you able to find any workaround for this?

I workedaround it by rewritting the metric key and replace the dots by another non-reserved character used on JSON path. (underscore for example)

**Comment by dushshantha** [comment]
@andrealexandre Thanks for the response. Yes, I was keeping that as a last resort.

**Comment by mikkeloscar** [comment]
@dushshantha and @andrealexandre I have made a PR #192 which enables support for keys with dots in them as requested here. Basically the option was to use a different jsonPath library with support for this.

I would appreciate if you could help test it by validating that it works for your use cases. Here is an image built from the PR:

```
registry.opensource.zalan.do/teapot/kube-metrics-adapter-test:pr-192-1
```
