### ISSUE TITLE
kube-metrics-adapter using multiple prometheus in different namespaces

### ISSUE THREAD

**Issue by palmerabollo** [zalando-incubator/kube-metrics-adapter#93]
## Expected Behavior

When you have 2 HorizontalPodAutoscalers using annotations to specify the prometheus server (e.g. `metric-config.external.prometheus-query.prometheus/prometheus-server: http://my-prometheus`), metrics should be read from the prometheus server in the annotation.

## Actual Behavior

The prometheus-server defined in the kube-metrics-server flags is used instead of using the value in the `metric-config.external.prometheus-query.prometheus/prometheus-server` annotation.

## Steps to Reproduce the Problem

  1. Deploy two prometheus servers in two different namespaces.
  2. Create two HPAs using the `metric-config.external.prometheus-query.prometheus/prometheus-server` annotation. Each HPA should use one of the prometheus servers.
  3. Verify that the annotation is not honored.

## Specifications

  - Version: v0.0.4
  - Platform: kubernetes 1.14.6
  - Subsystem: -

**Comment by mikkeloscar** [comment]
I can not replicate this issue.

Using the example HPA from the README. I create two HPAs in different namespaces and observe the following in the kube-metrics-adapter logs:

```
kube-metrics-adapter-5c87f994d6-26cbm kube-metrics-adapter time="2019-11-25T14:47:43Z" level=error msg="Failed to collect metrics: Get http://prometheus.my-namespace.svc/api/v1/query?query=scalar%28sum%28rate%28event-service_events_count%7Bapplication%3D%22event-service%22%2Cprocessed%3D%22true%22%7D%5B1m%5D%29%29%29%0A&time=2019-11-25T14%3A47%3A43.082778306Z: dial tcp: lookup prometheus.my-namespace.svc on 10.149.64.76:53: no such host" provider=hpa
kube-metrics-adapter-5c87f994d6-26cbm kube-metrics-adapter time="2019-11-25T14:47:43Z" level=info msg="Collected 0 new metric(s)" provider=hpa
kube-metrics-adapter-5c87f994d6-26cbm kube-metrics-adapter time="2019-11-25T14:47:43Z" level=error msg="Failed to collect metrics: Get http://prometheus.my-namespace2.svc/api/v1/query?query=scalar%28sum%28rate%28event-service_events_count%7Bapplication%3D%22event-service%22%2Cprocessed%3D%22true%22%7D%5B1m%5D%29%29%29%0A&time=2019-11-25T14%3A47%3A43.082739022Z: dial tcp: lookup prometheus.my-namespace2.svc on 10.149.64.76:53: no such host" provider=hpa
```

I didn't actually set up the Prometheus servers but this indicates it tries to go to the one defined as an annotation.

Could you share the full hpa manifest you use for this issue to trigger?

**Comment by palmerabollo** [comment]
Thanks for your prompt reply, Mikkel. Let me try to reproduce it again to share the minimal manifest and to doule chech that it's not something in our side. We use Thanos in front of Prometheus, but it should expose the same Prometheus API.

**Comment by mikkeloscar** [comment]
Will close this for now. Please re-open if you still need help.
