### ISSUE TITLE
OpenAPI spec does not exist

### ISSUE THREAD

**Issue by anderseknert** [zalando-incubator/kube-metrics-adapter#99]
Hi guys! More of an annoyance than anything else really, but would nice if we could avoid having the API server stop spewing logs about "OpenAPI spec does not exist" for the `v1beta1.external.metrics.k8s.io` and `v1beta1.custom.metrics.k8s.io` objects.

## Expected Behavior

API server logs not full of messages like:

```
1 controller.go:114] loading OpenAPI spec for "v1beta1.external.metrics.k8s.io" failed with: OpenAPI spec does not exist
1 controller.go:114] loading OpenAPI spec for "v1beta1.custom.metrics.k8s.io" failed with: OpenAPI spec does not exist
```

## Actual Behavior

API server logs full of messages like that.

I guess the best course of action would be to expose OpenAPI specs for those 2 objects - found this [commit elsewhere](https://github.com/kubernetes-sigs/metrics-server/pull/65/commits/06bcca5d06eae0a46fd1909a733e9f8be85b74d1) which seemed to detail a similar annoyance.

Anyway, thanks for kube-metrics-adapter!

**Comment by szuecs** [comment]
Do you want to create a pr?

**Comment by anderseknert** [comment]
I don't currently have the bandwidth to do so, but will check back once I do to see if this is still open.

**Comment by mikkeloscar** [comment]
Here is a PR to add support in the library we use: https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/65 if this is merged it would be simple to fix the issue I guess.
